name: linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: install dependencies
      run: sudo apt-get install libglfw3-dev
    - name: build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DTEST=1 ..
        make
    - name: test
      run: |
        cd build
        make test
    - name: upload
      uses: actions/upload-artifact@v7
      with:
        name: cboy
        path: build/cboy/cboy