name: linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install freeglut3-dev
    - name: build
      run: |
        mkdir build && cd build
        cmake -DTEST=1 ..
        make
    - name: test
      run: |
        cd build
        make test