name: macos

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        make
