name: windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: vcpkg install freeglut:x64-windows
    - name: build
      run: |
        mkdir build && cd build
        cmake -T "LLVM" -DCMAKE_TOOLCHAIN_FILE=[vcpkg root]\scripts\buildsystems\vcpkg.cmake ..
        make
